AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Environment:
      Variables:
        TABLE_NAME: userscores

Resources:
  #myDB:
  #  Type: AWS::Serverless::SimpleTable
  #  Properties:
  #    TableName: userscores
  #    PrimaryKey:
  #      Name: userId
  #      Type: String
  myDB:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: userscores
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: score
          AttributeType: S
        - AttributeName: createdDate
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: userId
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      GlobalSecondaryIndexes:
        - IndexName: score-index
          KeySchema:
            - AttributeName: score
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: '5'
            WriteCapacityUnits: '5'  
        - IndexName: createdDate-index
          KeySchema:
            - AttributeName: createdDate
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: '5'
            WriteCapacityUnits: '5'
 
            
  LambdaWrite:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functionWrite/
      Handler: write.handler
      Runtime: nodejs16.x
      Events:
        apiForLambdaWrite:
          Type: Api 
          Properties:
            Path: /writedb
            Method: post
      Policies: 
        - DynamoDBCrudPolicy:
            TableName: !Ref myDB
        - AWSLambdaBasicExecutionRole
            
  LambdaRead:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functionRead/
      Handler: read.handler
      Runtime: nodejs16.x
      Events:
        apiForLambdaRead:
          Type: Api 
          Properties:
            Path: /readdb
            Method: get
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref myDB
        - AWSLambdaBasicExecutionRole
       

Outputs:
  apiForLambdaWrite:
    Description: "API Gateway endpoint URL for Prod stage for write function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/writedb/"

  apiForLambdaRead:
    Description: "API Gateway endpoint URL for Prod stage for read function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/readdb/"